CREATE DATABASE bankingDB;
USE bankingDB;


  CREATE TABLE HDFC_BRANCH (
     HDFC_ACCT_NO INT NOT NULL AUTO_INCREMENT,
     HDFC_BRNCH_NM VARCHAR(30) NOT NULL,
     HDFC_BRNCH_IFSC VARCHAR(30) NOT NULL,
     PRIMARY KEY (HDFC_ACCT_NO)
  )ENGINE=InnoDB;
  
  CREATE TABLE HDFC_USR_INFO (
     USR_ACCT_NO int NOT NULL,
     USR_NM VARCHAR(30) NOT NULL,
     USR_EMAIL VARCHAR(30) NOT NULL,
     USR_GENDER VARCHAR(30) NOT NULL,
     USR_ADDRESS VARCHAR(30) NOT NULL,
     USR_USRNAME VARCHAR(30) NOT NULL,
     USR_PWD VARCHAR(30) NOT NULL,
     PRIMARY KEY (USR_ACCT_NO)
  );
  
  insert into HDFC_USR_INFO value (100,'Hemanth','pk@gmail.com','male','hyd','phk09','johnny');
  
  SELECT * FROM HDFC_ACC_NO;
  SELECT * FROM HDFC_USR_INFO;
 