CREATE DATABASE systemDB;
USE systemDB;

CREATE  TABLE `STUDENT_INFO` (
  `S_ID` INT NOT NULL ,
  `S_NAME` VARCHAR(45) NOT NULL ,
  `S_EMAIL` VARCHAR(45) NOT NULL ,
  `S_ADDRESS` VARCHAR(45) NOT NULL ,
  `S_UPDT_TS` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`S_ID`) );
  
  
  DESC STUDENT_INFO;
  DESC COURSE_INFO;
  DESC DEPT_INFO;
  
  SELECT * FROM STUDENT_INFO;
  SELECT * FROM COURSE_INFO;
  SELECT * FROM DEPT_INFO;